apiVersion: v2
name: dxemssql
description: "Helm chart for DH2i's DxEnterprise clustering solution with SQL Server availability groups"
type: application
appVersion: "22.0"
version: "0.5.1"
icon: http://10.1.201.236/img/dh2i-32x32.png
annotations:
  catalog.cattle.io/display-name: "DxEnterprise for Microsoft SQL AG"