# Default values for dxemssql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#General
replicas: 3
secretKeys: null
enableLoadBalancers: "true"

#SQL Server settings
sqlImage:
  repository: "mcr.microsoft.com/mssql/server"
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "2022-latest"
ACCEPT_EULA: "Y"
MSSQL_AGENT_ENABLED: "false"

#DxEnterprise settings
dxeImage:
  repository: intreg.dh2i.com/dxe
  pullPolicy: Always
  tag: latest
DX_LICENSE: null
DX_VHOST_NAME: "VHOST1"
DX_AG_NAME: "AG1"
DX_NEW_CLUSTER: "true"

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
